first:
  _target_: src.datasets.FakeAVCelebsDataset
  name: "test-set-1-balanced"
  instance_transforms: ${transforms.instance_transforms.inference}
second:
  _target_: src.datasets.FakeAVCelebsDataset
  name: "test-set-2-balanced"
  instance_transforms: ${transforms.instance_transforms.inference}