train:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "train"
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-set-1"
  instance_transforms: ${transforms.instance_transforms.inference}