test_faceswap:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-faceswap"
  instance_transforms: ${transforms.instance_transforms.inference}
test_fsgan:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-fsgan"
  instance_transforms: ${transforms.instance_transforms.inference}
test_wav2lip:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-wav2lip"
  instance_transforms: ${transforms.instance_transforms.inference}
test_rtvc:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-rtvc"
  instance_transforms: ${transforms.instance_transforms.inference}
test_faceswap_wav2lip:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-faceswap-wav2lip"
test_fsgan_wav2lip:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-wav2lip"
  instance_transforms: ${transforms.instance_transforms.inference}
test_set_1:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-set-1"
  instance_transforms: ${transforms.instance_transforms.inference}
test_set_2:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-set-2"
  instance_transforms: ${transforms.instance_transforms.inference}