train:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "one_batch"
  instance_transforms: ${transforms.instance_transforms.inference}
test_set_1:
  _target_: src.datasets.FeatsFakeAVCelebsDataset
  name: "test-set-1"
  instance_transforms: ${transforms.instance_transforms.inference}