defaults:
  - model: baseline
  - writer: wandb
  - metrics: pages
  - datasets: fakeavcelebs
  - dataloader: dataloader
  - transforms: example
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.WeightedCrossEntropyLoss
trainer:
  log_step: 50
  n_epochs: 30
  epoch_len: 2545
  device_tensors: ["vivit_frames", "av_video", "av_audio", "aasist_audio", "labels"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max test_Accuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "first_run_mlp"
  seed: 1
