defaults:
  - model: aasist_model
  - writer: wandb_inf
  - metrics: inference_full
  - datasets: fakeavcelebs_full 
  - dataloader: dataloader
  - transforms: example
  - _self_
inferencer:
  device_tensors: ["vivit_feats", "av_feats", "aasist_audio", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "inference/fakeavcelebs" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/aasist_full/model_best.pth" # path to the pretrained model
