model:
  _target_: src.model.BaselineModel
  av_channels: 768
  vivit_channels: 768
  as_channels: 64
  hidden_channels: 512
  dropout: 0.1
writer:
  _target_: src.logger.WandBWriter
  project_name: pytorch_template
  entity: null
  run_name: baseline
  mode: online
  loss_names:
  - loss
  log_checkpoints: false
  id_length: 8
  run_id: diawj68x
metrics:
  device: auto
  train:
  - _target_: src.metrics.AccuracyMetric
    device: ${metrics.device}
    name: TRAIN_Accuracy
  - _target_: src.metrics.PrecisionMetric
    device: ${metrics.device}
    name: TRAIN_Precision
  - _target_: src.metrics.RecallMetric
    device: ${metrics.device}
    name: TRAIN_Recall
  inference:
  - _target_: src.metrics.AccuracyMetric
    device: ${metrics.device}
    name: Accuracy
  - _target_: src.metrics.PrecisionMetric
    device: ${metrics.device}
    name: Precision
  - _target_: src.metrics.RecallMetric
    device: ${metrics.device}
    name: Recall
datasets:
  train:
    _target_: src.datasets.FakeAVCelebsDataset
    name: train
    instance_transforms: ${transforms.instance_transforms.inference}
  test:
    _target_: src.datasets.FakeAVCelebsDataset
    name: test-set-1
    instance_transforms: ${transforms.instance_transforms.inference}
dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 1
  pin_memory: true
transforms:
  batch_transforms:
    train: null
    inference: null
  instance_transforms:
    train: null
    inference: null
optimizer:
  _target_: torch.optim.Adam
  lr: 1.0e-05
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  gamma: 0.9
  step_size: ${trainer.epoch_len}
loss_function:
  _target_: src.loss.CrossEntropyLoss
trainer:
  log_step: 50
  n_epochs: 30
  epoch_len: 2545
  device_tensors:
  - vivit_frames
  - av_video
  - av_audio
  - aasist_audio
  - labels
  resume_from: null
  device: auto
  override: true
  monitor: max test_Accuracy
  save_period: 1
  early_stop: ${trainer.n_epochs}
  save_dir: first_run_mlp
  seed: 1
